/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "GestorBiblioteca.h"
#include <unistd.h>
#include <stdio.h>

// Macros para el color verde, usando estilo UNIX:
#define GREEN_ON "\x1b[32m"
#define GREEN_OFF "\x1b[0m"

int menuPrincipal();
int menuAdministracion();
void esperarEntradaPorConsola();

void gestorbiblioteca_1(char *host)
{
	CLIENT *clnt;
	int *result_1;
	int conexion_1_arg;
	bool_t *result_2;
	int desconexion_1_arg;
	int *result_3;
	TConsulta cargardatos_1_arg;
	bool_t *result_4;
	int guardardatos_1_arg;
	int *result_5;
	TNuevo nuevolibro_1_arg;
	int *result_6;
	TComRet comprar_1_arg;
	int *result_7;
	TComRet retirar_1_arg;
	bool_t *result_8;
	TOrdenacion ordenar_1_arg;
	int *result_9;
	int nlibros_1_arg;
	int *result_10;
	TConsulta buscar_1_arg;
	TLibro *result_11;
	TPosicion descargar_1_arg;
	int *result_12;
	TPosicion prestar_1_arg;
	int *result_13;
	TPosicion devolver_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, GESTORBIBLIOTECA, GESTORBIBLIOTECA_VER, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */
	int opcionElegida = -1;
	int contrasenha = 0;
	int idAdministrador = 0;
	Cadena nombreFichero = "";
	int NumLibros = 0;
	TLibro libro = {}; // Los struct se inicializan así.
	Cadena isbn = "";
	Cadena autor = "";
	Cadena titulo = "";
	int anio = 0;
	Cadena pais = "";
	Cadena idioma = "";
	TNuevo nuevoLibro = {};
	int campoElegido = 0;
	Cadena textoABuscar = "";
	char codigoBusqueda = '\0';
	int posicion = 0;
	Cadena textoCampo = "";
	char *punteroBusqueda = NULL;			 // Fuente: https://stackoverflow.com/questions/22508629/how-to-return-value-using-strstr-function
	char *punteroAlgunaCoincidencia[5] = {}; // Array de punteros para la búsqueda en todos los campos (*).
	Cadena isbnCompra = "";
	char confirmacionCompra = '\0';
	int numeroLibrosComprados = 0;
	int numeroLibrosRetirados = 0;

	do
	{
		opcionElegida = menuPrincipal();
		switch (opcionElegida)
		{
		case 0:
		{
			printf("Cerrando programa...\n");
			break;
		}
		case 1:
		{
			printf("Por favor inserte la contraseña de Administracion:\n");
			scanf("%d", &contrasenha);
			conexion_1_arg = contrasenha;
			result_1 = conexion_1(&conexion_1_arg, clnt);
			if (result_1 == (int *)NULL)
			{
				clnt_perror(clnt, "call failed");
			}
			else if (*result_1 == -2)
			{
				printf("ERROR: la contrasenha introducida es incorrecta\n");
			}
			else if (*result_1 == -1)
			{
				printf("ERROR: ya hay un administrador logueado\n");
			}
			else
			{
				idAdministrador = *result_1; // Guardamos el id generado por el servidor en el cliente administrador.
				printf("*** Contraseña correcta, puede acceder al menu de Administracion.**\n");
				esperarEntradaPorConsola(); // Esperamos a que el usuario pulse cualquier tecla.
				do
				{
					opcionElegida = menuAdministracion();
					switch (opcionElegida)
					{
					case 0:
					{
						desconexion_1_arg = idAdministrador;
						result_2 = desconexion_1(&desconexion_1_arg, clnt);
						if (result_2 == (bool_t *)NULL)
						{
							clnt_perror(clnt, "call failed");
						}
						else if (*result_2 == FALSE)
						{
							printf("ERROR: el id administrador no coincide con el del servidor\n");
						}
						else if (*result_2 == TRUE)
						{
							printf("Ha cerrado sesion con exito\n");
						}
						break;
					}
					case 1:
					{
						printf("Introduce el nombre del fichero de datos:\n");
						scanf("%s", nombreFichero);
						strcpy(cargardatos_1_arg.Datos, nombreFichero);
						cargardatos_1_arg.Ida = idAdministrador;
						result_3 = cargardatos_1(&cargardatos_1_arg, clnt);
						if (result_3 == (int *)NULL)
						{
							clnt_perror(clnt, "call failed");
						}
						else if (*result_3 == -1)
						{
							printf("ERROR: ya hay un administrador logueado\n");
						}
						else if (*result_3 == 0)
						{
							printf("ERROR: error al cargar los datos\n");
						}
						else if (*result_3 == 1)
						{
							printf("Datos cargados y ordenados correctamente\n");
						}
						break;
					}
					case 2:
					{
						// Guardamos los datos de la biblioteca en el fichero.
						guardardatos_1_arg = idAdministrador; // Le pasamos el id del administrador.
						result_4 = guardardatos_1(&guardardatos_1_arg, clnt);
						if (result_4 == (bool_t *)NULL)
						{
							clnt_perror(clnt, "call failed");
						}
						else if (*result_4 == FALSE)
						{
							printf("ERROR: no se ha podido la informacion en el fichero\n");
						}
						else
						{
							printf("Informacion salvada en el fichero correctamente\n");
						}
						break;
					}
					case 3:
					{
						// Pedimos los datos del nuevo libro:
						printf("Introduce el Isbn:\n");
						scanf("%s", isbn);
						printf("Introduce el Autor:\n");
						scanf("%s", autor);
						printf("Introduce el Titulo:\n");
						scanf("%s", titulo);
						printf("Introduce el anio:\n");
						scanf("%d", &anio);
						printf("Introduce el Pais:\n");
						scanf("%s", pais);
						printf("Introduce el Idioma:\n");
						scanf("%s", idioma);

						// Llenamos la variable libro:
						strcpy(libro.Isbn, isbn);
						strcpy(libro.Autor, autor);
						strcpy(libro.Titulo, titulo);
						libro.Anio = anio;
						strcpy(libro.Pais, pais);
						strcpy(libro.Idioma, idioma);

						// Inicializamos los valores no pedidos por consola:
						libro.NoLibros = 0;
						libro.NoListaEspera = 0;
						libro.NoPrestados = 0;

						nuevoLibro.Libro = libro;		  // Guardamos libro en el campo de nuevoLibro.
						nuevoLibro.Ida = idAdministrador; // Guardamos el id administrador en el campo de nuevoLibro.
						nuevolibro_1_arg = nuevoLibro;	  // Lo pasamos por argumento.
						result_5 = nuevolibro_1(&nuevolibro_1_arg, clnt);
						if (result_5 == (int *)NULL)
						{
							clnt_perror(clnt, "call failed");
						}
						else if (*result_5 == -1)
						{
							printf("ERROR: ya hay un administrador logueado\n");
						}
						else if (*result_5 == 0)
						{
							printf("ERROR: ya hay un libro registrado con el ISBN dado\n");
						}
						else if (*result_5 == 1)
						{
							printf("Se ha anhadido el nuevo libro correctamente\n");
						}
						break;
					}
					case 4:
					{
						printf("Introduce Isbn a Buscar:\n");
						scanf("%s", isbnCompra);
						// Por ISBN.
						strcpy(buscar_1_arg.Datos, isbnCompra);
						buscar_1_arg.Ida = idAdministrador;
						result_10 = buscar_1(&buscar_1_arg, clnt);
						if (result_10 == (int *)NULL)
						{
							clnt_perror(clnt, "call failed");
						}
						else if (*result_10 == -1)
						{
							printf("ERROR: no se ha encontrado ningun libro\n");
						}
						else if (*result_10 == -2)
						{
							printf("ERROR: ya hay un administrador logueado\n");
						}
						else
						{
							// Tenemos la posición del libro buscado en *result_10.
							descargar_1_arg.Pos = *result_10;				 // Pasamos la posición para descargarlo.
							result_11 = descargar_1(&descargar_1_arg, clnt); // Descargamos el libro.
							libro = *result_11;								 // Guardamos el libro en la variable libro.
							if (result_11 == (TLibro *)NULL)
							{
								clnt_perror(clnt, "call failed");
							}
							else
							{
								printf("%s\t%s\t%d\t%d\t%d\n", libro.Titulo, libro.Isbn, libro.NoLibros, libro.NoPrestados, libro.NoListaEspera);
								printf("%s\t%s(%s)\t%d\n", libro.Autor, libro.Pais, libro.Idioma, libro.Anio);
								printf("¿ Es este el libro al que desea comprar más unidades (s/n) ?\n");
								scanf(" %c", &confirmacionCompra);
								if (confirmacionCompra != 's')
								{ // Si el usuario no ha confirmado con s:
									printf("*** Compra abortada ***\n");
								}
								else
								{ // Si el usuario ha confirmado con s:
									printf("Introduce Numero de Libros comprados:\n");
									scanf("%d", &numeroLibrosComprados);
									// Pasamos los parámetros:
									comprar_1_arg.Ida = idAdministrador;
									strcpy(comprar_1_arg.Isbn, isbnCompra);
									comprar_1_arg.NoLibros = numeroLibrosComprados;
									result_6 = comprar_1(&comprar_1_arg, clnt);
									if (result_6 == (int *)NULL)
									{
										clnt_perror(clnt, "call failed");
									}
									else if (*result_6 == -1)
									{
										printf("ERROR: ya hay un administrador logueado\n");
									}
									else if (*result_6 == 0)
									{
										printf("ERROR: no se ha encontrado el libro\n");
									}
									else if (*result_6 == 1)
									{
										printf("*** Se han agregado los nuevos ejemplares del libro y los datos están ordenados ***\n");
									}
								}
							}
						}
						break;
					}
					case 5:
					{
						printf("Introduce Isbn a Buscar:\n");
						scanf("%s", isbnCompra);
						// Por ISBN.
						strcpy(buscar_1_arg.Datos, isbnCompra);
						buscar_1_arg.Ida = idAdministrador;
						result_10 = buscar_1(&buscar_1_arg, clnt);
						if (result_10 == (int *)NULL)
						{
							clnt_perror(clnt, "call failed");
						}
						else if (*result_10 == -1)
						{
							printf("ERROR: no se ha encontrado ningun libro\n");
						}
						else if (*result_10 == -2)
						{
							printf("ERROR: ya hay un administrador logueado\n");
						}
						else
						{
							// Tenemos la posición del libro buscado en *result_10.
							descargar_1_arg.Pos = *result_10;				 // Pasamos la posición para descargarlo.
							result_11 = descargar_1(&descargar_1_arg, clnt); // Descargamos el libro.
							libro = *result_11;								 // Guardamos el libro en la variable libro.
							if (result_11 == (TLibro *)NULL)
							{
								clnt_perror(clnt, "call failed");
							}
							else
							{
								printf("%s\t%s\t%d\t%d\t%d\n", libro.Titulo, libro.Isbn, libro.NoLibros, libro.NoPrestados, libro.NoListaEspera);
								printf("%s\t%s(%s)\t%d\n", libro.Autor, libro.Pais, libro.Idioma, libro.Anio);
								printf("¿ Es este el libro al que desea retirar unidades (s/n) ?\n");
								scanf(" %c", &confirmacionCompra);
								if (confirmacionCompra != 's')
								{ // Si el usuario no ha confirmado con s:
									printf("*** Retiro abortado ***\n");
								}
								else
								{
									printf("Introduce Numero de unidades a retirar:\n");
									scanf("%d", &numeroLibrosRetirados);
									// Preparamos los argumentos:
									retirar_1_arg.Ida = idAdministrador;
									strcpy(retirar_1_arg.Isbn, libro.Isbn);
									retirar_1_arg.NoLibros = numeroLibrosRetirados;
									result_7 = retirar_1(&retirar_1_arg, clnt);
									if (result_7 == (int *)NULL)
									{
										clnt_perror(clnt, "call failed");
									}
									else if (*result_7 == -1)
									{
										printf("ERROR: ya hay un administrador logueado\n");
									}
									else if (*result_7 == 0)
									{
										printf("ERROR: no se ha encontrado ningun libro\n");
									}
									else if (*result_7 == 2)
									{
										printf("ERROR: no hay suficientes ejemplares para ser retirados\n");
									}
									else if (*result_7 == 1)
									{
										printf("Se han reducido el número de ejemplares disponibles y se han ordenado los datos\n");
									}
								}
							}
						}
						break;
					}
					case 6:
					{
						printf("0.- Por Isbn\n");
						printf("1.- Por Titulo\n");
						printf("2.- Por Autor\n");
						printf("3.- Por Anho\n");
						printf("4.- Por Pais\n");
						printf("5.- Por Idioma\n");
						printf("6.- Por nº de libros Disponibles\n");
						printf("7.- Por nº de libros Prestados\n");
						printf("8.- Por nº de libros en Espera\n");
						printf("Elige el campo que ordenara los libros:\n");
						scanf("%d", &campoElegido);
						// Preparamos el argumento:
						ordenar_1_arg.Campo = campoElegido;
						ordenar_1_arg.Ida = idAdministrador;
						// Llamamos a ordenar en el servidor:
						result_8 = ordenar_1(&ordenar_1_arg, clnt);
						if (result_8 == (bool_t *)NULL)
						{
							clnt_perror(clnt, "call failed");
						}
						else if (*result_8 == FALSE)
						{
							printf("ERROR: el id administrador no coincide con el del servidor\n");
						}
						else if (*result_8 == TRUE)
						{
							printf("Se ha ordenado correctamente el vector\n");
						}
						break;
					}
					case 7:
					{
						printf("Introduce el texto a buscar:\n");
						scanf("%s", textoABuscar);
						printf("I.- Por Isbn\n");
						printf("T.- Por Titulo\n");
						printf("A.- Por Autor\n");
						printf("P.- Por Pais\n");
						printf("D.- Por Idioma\n");
						printf("*.- Por todos los campos\n");
						printf("Introduce el codigo de busqueda\n");
						scanf(" %c", &codigoBusqueda); // Para que el salto de línea de textoABuscar no nos fastidie, ponemos un espacio.

						if (codigoBusqueda == 'I')
						{
							// Por ISBN.
							strcpy(buscar_1_arg.Datos, textoABuscar);
							buscar_1_arg.Ida = idAdministrador;
							result_10 = buscar_1(&buscar_1_arg, clnt);
							if (result_10 == (int *)NULL)
							{
								clnt_perror(clnt, "call failed");
							}
							else if (*result_10 == -1)
							{
								printf("ERROR: no se ha encontrado ningun libro\n");
							}
							else if (*result_10 == -2)
							{
								printf("ERROR: ya hay un administrador logueado\n");
							}
							else
							{
								// Tenemos la posición del libro buscado en *result_10.
								descargar_1_arg.Pos = *result_10;				 // Pasamos la posición para descargarlo.
								result_11 = descargar_1(&descargar_1_arg, clnt); // Descargamos el libro.
								libro = *result_11;								 // Guardamos el libro en la variable libro.
								if (result_11 == (TLibro *)NULL)
								{
									clnt_perror(clnt, "call failed");
								}
								else
								{
									printf("%s\t%s\t%d\t%d\t%d\n", libro.Titulo, libro.Isbn, libro.NoLibros, libro.NoPrestados, libro.NoListaEspera);
									printf("%s\t%s(%s)\t%d\n", libro.Autor, libro.Pais, libro.Idioma, libro.Anio);
								}
							}
						}
						else
						{
							// Si no buscamos por ISBN, descargaremos cada libro y filtraremos:
							result_9 = nlibros_1(&nlibros_1_arg, clnt); // Recogemos el nº de libros del servidor.
							if (result_9 == (int *)NULL)
							{
								clnt_perror(clnt, "call failed");
							}
							else
							{
								printf("POS\tTITULO\tISBN\tDIS\tPRE\tPOS\n");
								printf("\tAUTOR\tPAIS (IDIOMA)\tANIO\n");
								printf("*********************************************************************************************\n");

								NumLibros = *result_9; // Guardamos el resultado en la variable del cliente.

								descargar_1_arg.Ida = idAdministrador; // Le pasamos al servidor nuestro id.

								// Descargaremos cada libro del servidor. Si pasa el filtrado, lo mostraremos por pantalla:
								for (int i = 0; i < NumLibros; i++)
								{
									descargar_1_arg.Pos = i;						 // Iteramos usando descargar_1_arg e i.
									result_11 = descargar_1(&descargar_1_arg, clnt); // Descarga el libro i.
									if (result_11 == (TLibro *)NULL)
									{
										clnt_perror(clnt, "call failed");
									}
									else
									{
										libro = *result_11; // Hemos recibido el resultado bien, podemos guardarlo en libro.
										// Solo mostraremos el libro si aparece la cadena buscada en los campos deseados.
										// Usaremos strstr, y un array de punteros.
										// Para la búsqueda monocampo, emplearemos el puntero respectivo: punteroAlgunaCoincidencia[i]. i valdrá lo que diga el mapa: {Isbn:0, Titulo:1, Autor:2, Pais:3, Idioma:4}.
										// Para la búsqueda multicampo (*), emplearemos todo el array de punteros: punteroAlgunaCoincidencia.

										switch (codigoBusqueda)
										{
										case 'T':
										{																	   // Por título.
											punteroAlgunaCoincidencia[1] = strstr(libro.Titulo, textoABuscar); // Titulo:1.
											// Inicializo el resto de punteros a NULL:
											punteroAlgunaCoincidencia[0] = NULL;
											punteroAlgunaCoincidencia[2] = NULL;
											punteroAlgunaCoincidencia[3] = NULL;
											punteroAlgunaCoincidencia[4] = NULL;
											break;
										}
										case 'A':
										{																	  // Por autor.
											punteroAlgunaCoincidencia[2] = strstr(libro.Autor, textoABuscar); // Autor:2.
											// Inicializo el resto de punteros a NULL:
											punteroAlgunaCoincidencia[0] = NULL;
											punteroAlgunaCoincidencia[1] = NULL;
											punteroAlgunaCoincidencia[3] = NULL;
											punteroAlgunaCoincidencia[4] = NULL;
											break;
										}
										case 'P':
										{																	 // Por país.
											punteroAlgunaCoincidencia[3] = strstr(libro.Pais, textoABuscar); // Pais:3.
											// Inicializo el resto de punteros a NULL:
											punteroAlgunaCoincidencia[0] = NULL;
											punteroAlgunaCoincidencia[1] = NULL;
											punteroAlgunaCoincidencia[2] = NULL;
											punteroAlgunaCoincidencia[4] = NULL;
											break;
										}
										case 'D':
										{																	   // Por idioma.
											punteroAlgunaCoincidencia[4] = strstr(libro.Idioma, textoABuscar); // Idioma:4.
											// Inicializo el resto de punteros a NULL:
											punteroAlgunaCoincidencia[0] = NULL;
											punteroAlgunaCoincidencia[1] = NULL;
											punteroAlgunaCoincidencia[2] = NULL;
											punteroAlgunaCoincidencia[3] = NULL;
											break;
										}
										case '*':
										{ // Por todos los campos.
											punteroAlgunaCoincidencia[0] = strstr(libro.Isbn, textoABuscar);
											punteroAlgunaCoincidencia[1] = strstr(libro.Titulo, textoABuscar);
											punteroAlgunaCoincidencia[2] = strstr(libro.Autor, textoABuscar);
											punteroAlgunaCoincidencia[3] = strstr(libro.Pais, textoABuscar);
											punteroAlgunaCoincidencia[4] = strstr(libro.Idioma, textoABuscar);
											break;
										}
										}

										if (punteroAlgunaCoincidencia[0] != NULL || punteroAlgunaCoincidencia[1] != NULL || punteroAlgunaCoincidencia[2] != NULL || punteroAlgunaCoincidencia[3] != NULL || punteroAlgunaCoincidencia[4] != NULL)
										{
											/*printf("%d\t%s\t%s\t%d\t%d\t%d\n", i, libro.Titulo, libro.Isbn, libro.NoLibros, libro.NoPrestados, libro.NoListaEspera);
											printf("%s\t%s(%s)\t%d\n", libro.Autor, libro.Pais, libro.Idioma, libro.Anio);*/
											printf("%d\t", i);

											if (punteroAlgunaCoincidencia[1] != NULL)
											{ // Si coincide el titulo (Titulo:1), lo coloreo:
												printf(GREEN_ON "%s" GREEN_OFF "\t", libro.Titulo);
											}
											else
											{ // Si no hay coincidencia simplemente lo escribo:
												printf("%s\t", libro.Titulo);
											}

											if (punteroAlgunaCoincidencia[0])
											{ // Si coincide el (Isbn:0), lo coloreo:
												printf(GREEN_ON "%s"
																"\t" GREEN_OFF,
													   libro.Isbn);
											}
											else
											{ // Si no hay coincidencia simplemente lo escribo:
												printf("%s\t", libro.Isbn);
											}

											printf("%d\t%d\t%d\n", libro.NoLibros, libro.NoPrestados, libro.NoListaEspera);

											if (punteroAlgunaCoincidencia[2] != NULL)
											{ // Si coincide el autor (Autor:2), lo coloreo:
												printf(GREEN_ON "%s" GREEN_OFF "\t", libro.Autor);
											}
											else
											{ // Si no hay coincidencia simplemente lo escribo:
												printf("%s\t", libro.Autor);
											}

											if (punteroAlgunaCoincidencia[3] != NULL)
											{ // Si coincide el pais (Pais:3), lo coloreo:
												printf(GREEN_ON "%s" GREEN_OFF "(", libro.Pais);
											}
											else
											{ // Si no hay coincidencia simplemente lo escribo:
												printf("%s(", libro.Pais);
											}

											if (punteroAlgunaCoincidencia[4] != NULL)
											{ // Si coincide el idioma (Idioma:4), lo coloreo:
												printf(GREEN_ON "%s" GREEN_OFF ")\t", libro.Idioma);
											}
											else
											{ // Si no hay coincidencia simplemente lo escribo:
												printf("%s)\t", libro.Idioma);
											}

											printf("%d\n", libro.Anio);
										}
									}
								}
							}
						}
						break;
					}
					case 8:
					{
						// Recogemos del servidor el numero de libros:
						nlibros_1_arg = idAdministrador;			// Le pasamos al servidor el id de administrador.
						result_9 = nlibros_1(&nlibros_1_arg, clnt); // Recogemos el nº de libros del servidor.
						if (result_9 == (int *)NULL)
						{
							clnt_perror(clnt, "call failed");
						}
						else
						{
							// Ya formatearemos guay la práctica y le meteremos musiquita, ahora nos debemos centrar en que funcione simplemente.
							printf("POS\tTITULO\tISBN\tDIS\tPRE\tPOS\n");
							printf("\tAUTOR\tPAIS (IDIOMA)\tANIO\n");
							printf("*********************************************************************************************\n");

							NumLibros = *result_9; // Guardamos el resultado en la variable del cliente.

							descargar_1_arg.Ida = idAdministrador; // Le pasamos al servidor nuestro id.

							// Descargamos cada libro del servidor y lo mostramos por pantalla:
							for (int i = 0; i < NumLibros; i++)
							{
								descargar_1_arg.Pos = i;						 // Iteramos usando descargar_1_arg e i.
								result_11 = descargar_1(&descargar_1_arg, clnt); // Descarga el libro i.
								if (result_11 == (TLibro *)NULL)
								{
									clnt_perror(clnt, "call failed");
								}
								else
								{
									// Hemos recibido el resultado bien, podemos guardarlo en libro y escribir por pantalla.
									libro = *result_11;
									printf("%d\t%s\t%s\t%d\t%d\t%d\n", i, libro.Titulo, libro.Isbn, libro.NoLibros, libro.NoPrestados, libro.NoListaEspera);
									printf("%s\t%s(%s)\t%d\n", libro.Autor, libro.Pais, libro.Idioma, libro.Anio);
								}
							}
						}
						break;
					}
					}
					esperarEntradaPorConsola(); // Esperamos a que el usuario pulse cualquier tecla.
				} while (opcionElegida != 0);
				opcionElegida = -1; // Si salimos del menú de administración, reseteamos la variable. Esto lo hacemos para evitar salir del menú principal.
			}
			break;
		}
		case 2: // Consulta de libros
		{
			printf("Introduce el texto a buscar:\n");
			scanf("%s", textoABuscar);
			printf("I.- Por Isbn\n");
			printf("T.- Por Titulo\n");
			printf("A.- Por Autor\n");
			printf("P.- Por Pais\n");
			printf("D.- Por Idioma\n");
			printf("*.- Por todos los campos\n");
			printf("Introduce el codigo de busqueda\n");
			scanf(" %c", &codigoBusqueda); // Para que el salto de línea de textoABuscar no nos fastidie, ponemos un espacio.

			printf("El texto a buscar es: %s\n", textoABuscar);

			if (codigoBusqueda == 'I')
			{
				// Por ISBN.
				strcpy(buscar_1_arg.Datos, textoABuscar);
				buscar_1_arg.Ida = idAdministrador;
				result_10 = buscar_1(&buscar_1_arg, clnt);
				if (result_10 == (int *)NULL)
				{
					clnt_perror(clnt, "call failed");
				}
				else if (*result_10 == -1)
				{
					printf("ERROR: no se ha encontrado ningun libro\n");
				}
				else if (*result_10 == -2)
				{
					printf("ERROR: ya hay un administrador logueado\n");
				}
				else
				{
					// Tenemos la posición del libro buscado en *result_10.
					descargar_1_arg.Pos = *result_10;				 // Pasamos la posición para descargarlo.
					result_11 = descargar_1(&descargar_1_arg, clnt); // Descargamos el libro.
					libro = *result_11;								 // Guardamos el libro en la variable libro.
					if (result_11 == (TLibro *)NULL)
					{
						clnt_perror(clnt, "call failed");
					}
					else
					{
						printf("%s\t%s\t%d\t%d\t%d\n", libro.Titulo, libro.Isbn, libro.NoLibros, libro.NoPrestados, libro.NoListaEspera);
						printf("%s\t%s(%s)\t%d\n", libro.Autor, libro.Pais, libro.Idioma, libro.Anio);
					}
				}
			}
			else
			{
				// Si no buscamos por ISBN, descargaremos cada libro y filtraremos:
				result_9 = nlibros_1(&nlibros_1_arg, clnt); // Recogemos el nº de libros del servidor.
				if (result_9 == (int *)NULL)
				{
					clnt_perror(clnt, "call failed");
				}
				else
				{
					printf("POS\tTITULO\tISBN\tDIS\n");
					printf("\tAUTOR\tPAIS (IDIOMA)\tANIO\n");
					printf("*********************************************************************************************\n");

					NumLibros = *result_9; // Guardamos el resultado en la variable del cliente.

					descargar_1_arg.Ida = idAdministrador; // Le pasamos al servidor nuestro id.

					// Descargaremos cada libro del servidor. Si pasa el filtrado, lo mostraremos por pantalla:
					for (int i = 0; i < NumLibros; i++)
					{
						descargar_1_arg.Pos = i;						 // Iteramos usando descargar_1_arg e i.
						result_11 = descargar_1(&descargar_1_arg, clnt); // Descarga el libro i.
						if (result_11 == (TLibro *)NULL)
						{
							clnt_perror(clnt, "call failed");
						}
						else
						{
							libro = *result_11; // Hemos recibido el resultado bien, podemos guardarlo en libro.
							// Solo mostraremos el libro si aparece la cadena buscada en los campos deseados.
							// Usaremos strstr, y un array de punteros.
							// Para la búsqueda monocampo, emplearemos el puntero respectivo: punteroAlgunaCoincidencia[i]. i valdrá lo que diga el mapa: {Isbn:0, Titulo:1, Autor:2, Pais:3, Idioma:4}.
							// Para la búsqueda multicampo (*), emplearemos todo el array de punteros: punteroAlgunaCoincidencia.

							switch (codigoBusqueda)
							{
							case 'T':
							{																	   // Por título.
								punteroAlgunaCoincidencia[1] = strstr(libro.Titulo, textoABuscar); // Titulo:1.
								// Inicializo el resto de punteros a NULL:
								punteroAlgunaCoincidencia[0] = NULL;
								punteroAlgunaCoincidencia[2] = NULL;
								punteroAlgunaCoincidencia[3] = NULL;
								punteroAlgunaCoincidencia[4] = NULL;
								break;
							}
							case 'A':
							{																	  // Por autor.
								punteroAlgunaCoincidencia[2] = strstr(libro.Autor, textoABuscar); // Autor:2.
								// Inicializo el resto de punteros a NULL:
								punteroAlgunaCoincidencia[0] = NULL;
								punteroAlgunaCoincidencia[1] = NULL;
								punteroAlgunaCoincidencia[3] = NULL;
								punteroAlgunaCoincidencia[4] = NULL;
								break;
							}
							case 'P':
							{																	 // Por país.
								punteroAlgunaCoincidencia[3] = strstr(libro.Pais, textoABuscar); // Pais:3.
								// Inicializo el resto de punteros a NULL:
								punteroAlgunaCoincidencia[0] = NULL;
								punteroAlgunaCoincidencia[1] = NULL;
								punteroAlgunaCoincidencia[2] = NULL;
								punteroAlgunaCoincidencia[4] = NULL;
								break;
							}
							case 'D':
							{																	   // Por idioma.
								punteroAlgunaCoincidencia[4] = strstr(libro.Idioma, textoABuscar); // Idioma:4.
								// Inicializo el resto de punteros a NULL:
								punteroAlgunaCoincidencia[0] = NULL;
								punteroAlgunaCoincidencia[1] = NULL;
								punteroAlgunaCoincidencia[2] = NULL;
								punteroAlgunaCoincidencia[3] = NULL;
								break;
							}
							case '*':
							{ // Por todos los campos.
								punteroAlgunaCoincidencia[0] = strstr(libro.Isbn, textoABuscar);
								punteroAlgunaCoincidencia[1] = strstr(libro.Titulo, textoABuscar);
								punteroAlgunaCoincidencia[2] = strstr(libro.Autor, textoABuscar);
								punteroAlgunaCoincidencia[3] = strstr(libro.Pais, textoABuscar);
								punteroAlgunaCoincidencia[4] = strstr(libro.Idioma, textoABuscar);
								break;
							}
							}

							if (punteroAlgunaCoincidencia[0] != NULL || punteroAlgunaCoincidencia[1] != NULL || punteroAlgunaCoincidencia[2] != NULL || punteroAlgunaCoincidencia[3] != NULL || punteroAlgunaCoincidencia[4] != NULL)
							{
								printf("%d\t%s\t%s\t%d\n", i, libro.Titulo, libro.Isbn, libro.NoLibros);
								printf("%s\t%s(%s)\t%d\n", libro.Autor, libro.Pais, libro.Idioma, libro.Anio);
							}
						}
					}
				}
			}
			break;
		}
		case 3: // Prestamo de libros
		{
			bool_t libroEncontrado = FALSE;
			printf("Introduce el texto a buscar:\n");
			scanf("%s", textoABuscar);
			printf("I.- Por Isbn\n");
			printf("T.- Por Titulo\n");
			printf("A.- Por Autor\n");
			printf("P.- Por Pais\n");
			printf("D.- Por Idioma\n");
			printf("*.- Por todos los campos\n");
			printf("Introduce el codigo de busqueda\n");
			scanf(" %c", &codigoBusqueda); // Para que el salto de línea de textoABuscar no nos fastidie, ponemos un espacio.

			if (codigoBusqueda == 'I')
			{
				// Por ISBN.
				strcpy(buscar_1_arg.Datos, textoABuscar);
				buscar_1_arg.Ida = idAdministrador;
				result_10 = buscar_1(&buscar_1_arg, clnt);
				if (result_10 == (int *)NULL)
				{
					clnt_perror(clnt, "call failed");
				}
				else if (*result_10 == -1)
				{
					printf("ERROR: no se ha encontrado ningun libro\n");
				}
				else if (*result_10 == -2)
				{
					printf("ERROR: ya hay un administrador logueado\n");
				}
				else
				{
					libroEncontrado = TRUE;
					// Tenemos la posición del libro buscado en *result_10.
					descargar_1_arg.Pos = *result_10;				 // Pasamos la posición para descargarlo.
					result_11 = descargar_1(&descargar_1_arg, clnt); // Descargamos el libro.
					libro = *result_11;								 // Guardamos el libro en la variable libro.
					if (result_11 == (TLibro *)NULL)
					{
						clnt_perror(clnt, "call failed");
					}
					else
					{
						printf("%s\t%s\t%d\t%d\t%d\n", libro.Titulo, libro.Isbn, libro.NoLibros, libro.NoPrestados, libro.NoListaEspera);
						printf("%s\t%s(%s)\t%d\n", libro.Autor, libro.Pais, libro.Idioma, libro.Anio);
					}
				}
			}
			else
			{
				// Si no buscamos por ISBN, descargaremos cada libro y filtraremos:
				result_9 = nlibros_1(&nlibros_1_arg, clnt); // Recogemos el nº de libros del servidor.
				if (result_9 == (int *)NULL)
				{
					clnt_perror(clnt, "call failed");
				}
				else
				{
					printf("POS\tTITULO\tISBN\tDIS\n");
					printf("\tAUTOR\tPAIS (IDIOMA)\tANIO\n");
					printf("*********************************************************************************************\n");

					NumLibros = *result_9; // Guardamos el resultado en la variable del cliente.

					descargar_1_arg.Ida = idAdministrador; // Le pasamos al servidor nuestro id.

					// Descargaremos cada libro del servidor. Si pasa el filtrado, lo mostraremos por pantalla:
					for (int i = 0; i < NumLibros; i++)
					{
						descargar_1_arg.Pos = i;						 // Iteramos usando descargar_1_arg e i.
						result_11 = descargar_1(&descargar_1_arg, clnt); // Descarga el libro i.
						if (result_11 == (TLibro *)NULL)
						{
							clnt_perror(clnt, "call failed");
						}
						else
						{
							libro = *result_11; // Hemos recibido el resultado bien, podemos guardarlo en libro.
							// Solo mostraremos el libro si aparece la cadena buscada en los campos deseados.
							// Usaremos strstr, y un array de punteros.
							// Para la búsqueda monocampo, emplearemos el puntero respectivo: punteroAlgunaCoincidencia[i]. i valdrá lo que diga el mapa: {Isbn:0, Titulo:1, Autor:2, Pais:3, Idioma:4}.
							// Para la búsqueda multicampo (*), emplearemos todo el array de punteros: punteroAlgunaCoincidencia.

							switch (codigoBusqueda)
							{
							case 'T':
							{												   // Por título.
								punteroAlgunaCoincidencia[1] = strstr(libro.Titulo, textoABuscar); // Titulo:1.
								// Inicializo el resto de punteros a NULL:
								punteroAlgunaCoincidencia[0] = NULL;
								punteroAlgunaCoincidencia[2] = NULL;
								punteroAlgunaCoincidencia[3] = NULL;
								punteroAlgunaCoincidencia[4] = NULL;
								break;
							}
							case 'A':
							{												  // Por autor.
								punteroAlgunaCoincidencia[2] = strstr(libro.Autor, textoABuscar); // Autor:2.
								// Inicializo el resto de punteros a NULL:
								punteroAlgunaCoincidencia[0] = NULL;
								punteroAlgunaCoincidencia[1] = NULL;
								punteroAlgunaCoincidencia[3] = NULL;
								punteroAlgunaCoincidencia[4] = NULL;
								break;
							}
							case 'P':
							{												 // Por país.
								punteroAlgunaCoincidencia[3] = strstr(libro.Pais, textoABuscar); // Pais:3.
								// Inicializo el resto de punteros a NULL:
								punteroAlgunaCoincidencia[0] = NULL;
								punteroAlgunaCoincidencia[1] = NULL;
								punteroAlgunaCoincidencia[2] = NULL;
								punteroAlgunaCoincidencia[4] = NULL;
								break;
							}
							case 'D':
							{												   // Por idioma.
								punteroAlgunaCoincidencia[4] = strstr(libro.Idioma, textoABuscar); // Idioma:4.
								// Inicializo el resto de punteros a NULL:
								punteroAlgunaCoincidencia[0] = NULL;
								punteroAlgunaCoincidencia[1] = NULL;
								punteroAlgunaCoincidencia[2] = NULL;
								punteroAlgunaCoincidencia[3] = NULL;
								break;
							}
							case '*':
							{ // Por todos los campos.
								punteroAlgunaCoincidencia[0] = strstr(libro.Isbn, textoABuscar);
								punteroAlgunaCoincidencia[1] = strstr(libro.Titulo, textoABuscar);
								punteroAlgunaCoincidencia[2] = strstr(libro.Autor, textoABuscar);
								punteroAlgunaCoincidencia[3] = strstr(libro.Pais, textoABuscar);
								punteroAlgunaCoincidencia[4] = strstr(libro.Idioma, textoABuscar);
								break;
							}
							}

							if (punteroAlgunaCoincidencia[0] != NULL || punteroAlgunaCoincidencia[1] != NULL || punteroAlgunaCoincidencia[2] != NULL || punteroAlgunaCoincidencia[3] != NULL || punteroAlgunaCoincidencia[4] != NULL)
							{
								libroEncontrado = TRUE;
								printf("%d\t%s\t%s\t%d\n", i, libro.Titulo, libro.Isbn, libro.NoLibros);
								printf("%s\t%s(%s)\t%d\n", libro.Autor, libro.Pais, libro.Idioma, libro.Anio);
							}
						}
					}
				}
			}
			if (libroEncontrado == TRUE)
			{
				char siono;
				printf("¿Quieres sacar algun libro de la biblioteca? (s/n):\n");
				scanf(" %c", &siono);
				if (siono != 's')
				{
					printf("Prestamo cancelado\n");
				}
				else
				{
					printf("Introduce la posicion del libro que quieres pedir prestado:\n");
					int posPrestar;
					scanf("%d", &posPrestar);
					prestar_1_arg.Ida = idAdministrador;
					prestar_1_arg.Pos = posPrestar;
					result_12 = prestar_1(&prestar_1_arg, clnt);
					if (result_12 == (int *)NULL)
					{
						clnt_perror(clnt, "call failed");
					}
					else if (*result_12 == -1)
					{
						printf("ERROR: La posicion introducida no es correcta\n");
					}
					else if (*result_12 == 0)
					{
						printf("No hay suficientes libros disponibles, entrando en lista de espera\n");
					}
					else if (*result_12 == 1)
					{
						printf("*** Se ha recogido el libro de forma exitosa ***\n");
					}
				}
			}
			break;
		}
		case 4: // Devolucion de libros
		{
			bool_t libroEncontrado = FALSE;
			printf("Introduce el texto a buscar:\n");
			scanf("%s", textoABuscar);
			printf("I.- Por Isbn\n");
			printf("T.- Por Titulo\n");
			printf("A.- Por Autor\n");
			printf("P.- Por Pais\n");
			printf("D.- Por Idioma\n");
			printf("*.- Por todos los campos\n");
			printf("Introduce el codigo de busqueda\n");
			scanf(" %c", &codigoBusqueda); // Para que el salto de línea de textoABuscar no nos fastidie, ponemos un espacio.

			if (codigoBusqueda == 'I')
			{
				// Por ISBN.
				strcpy(buscar_1_arg.Datos, textoABuscar);
				buscar_1_arg.Ida = idAdministrador;
				result_10 = buscar_1(&buscar_1_arg, clnt);
				if (result_10 == (int *)NULL)
				{
					clnt_perror(clnt, "call failed");
				}
				else if (*result_10 == -1)
				{
					printf("ERROR: no se ha encontrado ningun libro\n");
				}
				else if (*result_10 == -2)
				{
					printf("ERROR: ya hay un administrador logueado\n");
				}
				else
				{
					libroEncontrado = TRUE;
					// Tenemos la posición del libro buscado en *result_10.
					descargar_1_arg.Pos = *result_10;				 // Pasamos la posición para descargarlo.
					result_11 = descargar_1(&descargar_1_arg, clnt); // Descargamos el libro.
					libro = *result_11;								 // Guardamos el libro en la variable libro.
					if (result_11 == (TLibro *)NULL)
					{
						clnt_perror(clnt, "call failed");
					}
					else
					{
						printf("%s\t%s\t%d\t%d\t%d\n", libro.Titulo, libro.Isbn, libro.NoLibros, libro.NoPrestados, libro.NoListaEspera);
						printf("%s\t%s(%s)\t%d\n", libro.Autor, libro.Pais, libro.Idioma, libro.Anio);
					}
				}
			}
			else
			{
				// Si no buscamos por ISBN, descargaremos cada libro y filtraremos:
				result_9 = nlibros_1(&nlibros_1_arg, clnt); // Recogemos el nº de libros del servidor.
				if (result_9 == (int *)NULL)
				{
					clnt_perror(clnt, "call failed");
				}
				else
				{
					printf("POS\tTITULO\tISBN\tDIS\n");
					printf("\tAUTOR\tPAIS (IDIOMA)\tANIO\n");
					printf("*********************************************************************************************\n");

					NumLibros = *result_9; // Guardamos el resultado en la variable del cliente.

					descargar_1_arg.Ida = idAdministrador; // Le pasamos al servidor nuestro id.

					// Descargaremos cada libro del servidor. Si pasa el filtrado, lo mostraremos por pantalla:
					for (int i = 0; i < NumLibros; i++)
					{
						descargar_1_arg.Pos = i;						 // Iteramos usando descargar_1_arg e i.
						result_11 = descargar_1(&descargar_1_arg, clnt); // Descarga el libro i.
						if (result_11 == (TLibro *)NULL)
						{
							clnt_perror(clnt, "call failed");
						}
						else
						{
							libro = *result_11; // Hemos recibido el resultado bien, podemos guardarlo en libro.
							// Solo mostraremos el libro si aparece la cadena buscada en los campos deseados.
							// Usaremos strstr, y un array de punteros.
							// Para la búsqueda monocampo, emplearemos el puntero respectivo: punteroAlgunaCoincidencia[i]. i valdrá lo que diga el mapa: {Isbn:0, Titulo:1, Autor:2, Pais:3, Idioma:4}.
							// Para la búsqueda multicampo (*), emplearemos todo el array de punteros: punteroAlgunaCoincidencia.

							switch (codigoBusqueda)
							{
							case 'T':
							{												   // Por título.
								punteroAlgunaCoincidencia[1] = strstr(libro.Titulo, textoABuscar); // Titulo:1.
								// Inicializo el resto de punteros a NULL:
								punteroAlgunaCoincidencia[0] = NULL;
								punteroAlgunaCoincidencia[2] = NULL;
								punteroAlgunaCoincidencia[3] = NULL;
								punteroAlgunaCoincidencia[4] = NULL;
								break;
							}
							case 'A':
							{												  // Por autor.
								punteroAlgunaCoincidencia[2] = strstr(libro.Autor, textoABuscar); // Autor:2.
								// Inicializo el resto de punteros a NULL:
								punteroAlgunaCoincidencia[0] = NULL;
								punteroAlgunaCoincidencia[1] = NULL;
								punteroAlgunaCoincidencia[3] = NULL;
								punteroAlgunaCoincidencia[4] = NULL;
								break;
							}
							case 'P':
							{												 // Por país.
								punteroAlgunaCoincidencia[3] = strstr(libro.Pais, textoABuscar); // Pais:3.
								// Inicializo el resto de punteros a NULL:
								punteroAlgunaCoincidencia[0] = NULL;
								punteroAlgunaCoincidencia[1] = NULL;
								punteroAlgunaCoincidencia[2] = NULL;
								punteroAlgunaCoincidencia[4] = NULL;
								break;
							}
							case 'D':
							{												   // Por idioma.
								punteroAlgunaCoincidencia[4] = strstr(libro.Idioma, textoABuscar); // Idioma:4.
								// Inicializo el resto de punteros a NULL:
								punteroAlgunaCoincidencia[0] = NULL;
								punteroAlgunaCoincidencia[1] = NULL;
								punteroAlgunaCoincidencia[2] = NULL;
								punteroAlgunaCoincidencia[3] = NULL;
								break;
							}
							case '*':
							{ // Por todos los campos.
								punteroAlgunaCoincidencia[0] = strstr(libro.Isbn, textoABuscar);
								punteroAlgunaCoincidencia[1] = strstr(libro.Titulo, textoABuscar);
								punteroAlgunaCoincidencia[2] = strstr(libro.Autor, textoABuscar);
								punteroAlgunaCoincidencia[3] = strstr(libro.Pais, textoABuscar);
								punteroAlgunaCoincidencia[4] = strstr(libro.Idioma, textoABuscar);
								break;
							}
							}

							if (punteroAlgunaCoincidencia[0] != NULL || punteroAlgunaCoincidencia[1] != NULL || punteroAlgunaCoincidencia[2] != NULL || punteroAlgunaCoincidencia[3] != NULL || punteroAlgunaCoincidencia[4] != NULL)
							{
								libroEncontrado = TRUE;
								printf("%d\t%s\t%s\t%d\n", i, libro.Titulo, libro.Isbn, libro.NoLibros);
								printf("%s\t%s(%s)\t%d\n", libro.Autor, libro.Pais, libro.Idioma, libro.Anio);
							}
						}
					}
				}
			}
			if (libroEncontrado == TRUE)
			{
				char siono;
				printf("¿Quieres devolver algun libro de la biblioteca? (s/n):\n");
				scanf(" %c", &siono);
				if (siono != 's')
				{
					printf("Devolucion cancelada\n");
				}
				else
				{
					printf("Introduce la posicion del libro que quieres devolver:\n");
					int posDevolver;
					scanf("%d", &posDevolver);
					devolver_1_arg.Ida = idAdministrador;
					devolver_1_arg.Pos = posDevolver;
					result_13 = devolver_1(&devolver_1_arg, clnt);
					if (result_13 == (int *)NULL)
					{
						clnt_perror(clnt, "call failed");
					}
					else if (*result_13 == -1)
					{
						printf("ERROR: La posicion introducida no es correcta\n");
					}
					else if (*result_13 == 0)
					{
						printf("*** Se ha devuelto el libro y se le ha dado a alguen que estaba esperando ***\n");
					}
					else if (*result_13 == 1)
					{
						printf("*** Se ha devuelto el libro a su estanteria ***\n");
					}
					else if (*result_13 == 2)
					{
						printf("ERROR: no se ha podido devolver el libro porque no hay ni usuarios en lista de espera ni libros prestados\n");
					}
				}
			}
			break;
		}
		}
			if (opcionElegida != -1)
			{								// Si la opción elegida se ha introducido:
				esperarEntradaPorConsola(); // Esperamos a que el usuario pulse cualquier tecla.
			}
		}
		while (opcionElegida != 0)
			;
#ifndef DEBUG
		clnt_destroy(clnt);
#endif /* DEBUG */
	}

	int main(int argc, char *argv[])
	{
		char *host;

		if (argc < 2)
		{
			printf("usage: %s server_host\n", argv[0]);
			exit(1);
		}
		host = argv[1];
		gestorbiblioteca_1(host);
		exit(0);
	}
	int menuPrincipal()
	{
		int opcionElegida = -1;
		do
		{
			system("clear");
			printf("GESTOR BIBLIOTECARIO 1.0 (M. PRINCIPAL)\n");
			printf("***************************************\n");
			printf("\t1.- M. Administración\n");
			printf("\t2.- Consulta de libros\n");
			printf("\t3.- Préstamo de libros\n");
			printf("\t4.- Devolución de libros\n");
			printf("\t0.- Salir\n");
			printf("\n");
			printf("  Elige opción:\n");
			scanf("%d", &opcionElegida);
		} while (opcionElegida < 0 || opcionElegida > 4);
		return opcionElegida;
	}

	int menuAdministracion()
	{
		int opcionElegida = -1;
		do
		{
			system("clear");
			printf("GESTOR BIBLIOTECARIO 1.0 (M. ADMINISTRACION)\n");
			printf("********************************************\n");
			printf("\t1.- Cargar datos Biblioteca\n");
			printf("\t2.- Guardar datos Biblioteca\n");
			printf("\t3.- Nuevo libro\n");
			printf("\t4.- Comprar libros\n");
			printf("\t5.- Retirar libros\n");
			printf("\t6.- Ordenar libros\n");
			printf("\t7.- Buscar libros\n");
			printf("\t8.- Listar libros\n");
			printf("\t0.- Salir\n");
			printf("  Elige opción:\n");
			scanf("%d", &opcionElegida);
		} while (opcionElegida < 0 || opcionElegida > 8);
		return opcionElegida;
	}

	void esperarEntradaPorConsola()
	{
		printf("Introduzca cualquier numero para continuar.....\n");
		int noImporta = 0;
		scanf("%d", &noImporta);
	}